export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MOVIE_LIST_MORE_REQUEST = 'MOVIE_LIST_MORE_REQUEST';
export const MOVIE_LIST_MORE_SUCCESS = 'MOVIE_LIST_MORE_SUCCESS';
export const MOVIE_LIST_MORE_FAIL = 'MOVIE_LIST_MORE_FAIL';