export const MOVIE_DETAIL_LIST_REQUEST = 'MOVIE_DETAIL_LIST_REQUEST';
export const MOVIE_DETAIL_LIST_SUCCESS = 'MOVIE_DETAIL_LIST_SUCCESS';
export const MOVIE_DETAIL_LIST_FAIL = 'MOVIE_DETAIL_LIST_FAIL';
